### ISSUE TITLE
文档挂了？

### ISSUE THREAD

**Issue by hackeryutu** [easyj-projects/easyj-maven-plugin#1]
### 运行环境

- easyj-maven-plugin版本：
- spring-boot-maven-plugin版本：
- JDK版本：
- 操作系统：
- 其他版本信息：

### 堆栈或日志信息

```
请将完整的堆栈或日志信息粘贴在这里
```

### 如何复现该问题（请尽量提供最简短的步骤或代码）

1. xxx
2. xxx
3. xxx

**Comment by wangliang181230** [comment]
https://easyj.icu/docs/#/maven-plugin/
没有挂啊，我这还可以访问的。
